"""Economic model for customer demand simulation."""

from __future__ import annotations

import random
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.simulation.state import GameState

from src.simulation.state import (
    DailySummary,
    OrderStatus,
    ProductEconomics,
    Sale,
    SlotSize,
    WarehouseItem,
)

# =============================================================================
# Default Product Economics
# =============================================================================

# Default economics for products (used if not generated by LLM)
DEFAULT_ECONOMICS: dict[str, dict[str, float]] = {
    # Chips & Snacks
    "chips_lays_classic": {"reference_price": 1.75, "base_sales": 3.5, "elasticity": 1.2},
    "chips_doritos_nacho": {"reference_price": 1.85, "base_sales": 3.2, "elasticity": 1.3},
    "chips_cheetos_crunchy": {"reference_price": 1.65, "base_sales": 2.8, "elasticity": 1.2},
    "crackers_ritz": {"reference_price": 1.50, "base_sales": 1.5, "elasticity": 1.0},
    "pretzels_snyder": {"reference_price": 1.40, "base_sales": 1.8, "elasticity": 1.0},
    # Candy
    "candy_snickers": {"reference_price": 1.50, "base_sales": 4.0, "elasticity": 1.4},
    "candy_twix": {"reference_price": 1.50, "base_sales": 3.5, "elasticity": 1.4},
    "candy_mm_peanut": {"reference_price": 1.60, "base_sales": 3.0, "elasticity": 1.3},
    "candy_kitkat": {"reference_price": 1.45, "base_sales": 3.2, "elasticity": 1.3},
    "gum_orbit": {"reference_price": 1.25, "base_sales": 2.0, "elasticity": 0.9},
    # Drinks
    "drink_coke_can": {"reference_price": 1.75, "base_sales": 5.0, "elasticity": 1.5},
    "drink_pepsi_can": {"reference_price": 1.75, "base_sales": 4.0, "elasticity": 1.5},
    "drink_sprite_can": {"reference_price": 1.75, "base_sales": 3.0, "elasticity": 1.4},
    "water_dasani": {"reference_price": 1.50, "base_sales": 4.5, "elasticity": 1.2},
    "energy_redbull": {"reference_price": 3.00, "base_sales": 2.0, "elasticity": 1.8},
    "energy_monster": {"reference_price": 2.75, "base_sales": 2.5, "elasticity": 1.7},
    # Healthy
    "bar_kind_almond": {"reference_price": 2.25, "base_sales": 1.5, "elasticity": 1.1},
    "bar_clif_chocolate": {"reference_price": 2.15, "base_sales": 1.8, "elasticity": 1.1},
    "nuts_almonds": {"reference_price": 2.35, "base_sales": 1.2, "elasticity": 1.0},
    "fruit_dried_mix": {"reference_price": 2.00, "base_sales": 1.0, "elasticity": 1.0},
}

# Day of week multipliers (Monday=0 through Sunday=6)
DAY_OF_WEEK_MULTIPLIERS = {
    0: 1.0,  # Monday
    1: 1.0,  # Tuesday
    2: 1.1,  # Wednesday
    3: 1.1,  # Thursday
    4: 1.2,  # Friday
    5: 0.7,  # Saturday (lower traffic)
    6: 0.6,  # Sunday (lowest traffic)
}

# Monthly multipliers (1=January through 12=December)
MONTHLY_MULTIPLIERS = {
    1: 0.9,  # January (post-holiday slump)
    2: 0.95,
    3: 1.0,
    4: 1.0,
    5: 1.05,
    6: 1.1,  # Summer
    7: 1.1,
    8: 1.05,
    9: 1.0,  # Back to school
    10: 1.0,
    11: 1.05,
    12: 1.1,  # Holiday season
}


def get_day_of_week(day: int) -> int:
    """Get day of week (0=Monday) for a simulation day.

    Assumes simulation starts on a Monday (day 1).
    """
    return (day - 1) % 7


def get_month(day: int) -> int:
    """Get month (1-12) for a simulation day.

    Assumes simulation starts January 1st.
    """
    # Simplified: assume 30 days per month
    return ((day - 1) // 30) % 12 + 1


def get_product_economics(
    state: GameState, product_id: str, llm_client: Any | None = None
) -> ProductEconomics:
    """Get or generate economics for a product.

    Args:
        state: Current game state
        product_id: Product ID
        llm_client: Optional LLM client for generating economics

    Returns:
        ProductEconomics for the product
    """
    # Check cache first
    if product_id in state.product_economics:
        return state.product_economics[product_id]

    # Use default economics if available
    if product_id in DEFAULT_ECONOMICS:
        defaults = DEFAULT_ECONOMICS[product_id]
        economics = ProductEconomics(
            product_id=product_id,
            reference_price=defaults["reference_price"],
            base_sales=defaults["base_sales"],
            price_elasticity=defaults["elasticity"],
        )
    else:
        # Generate random economics for unknown products
        economics = ProductEconomics(
            product_id=product_id,
            reference_price=random.uniform(1.0, 3.0),
            base_sales=random.uniform(1.0, 4.0),
            price_elasticity=random.uniform(0.8, 1.5),
        )

    # Cache it
    state.product_economics[product_id] = economics
    return economics


def calculate_variety_multiplier(state: GameState) -> float:
    """Calculate multiplier based on product variety in machine.

    The benchmark rewards optimal variety (3-4 different products)
    and penalizes too many options (5+).

    Returns:
        Multiplier between 0.5 and 1.2
    """
    # Count unique products in machine
    unique_products = set()
    for slot in state.machine_slots:
        if slot.product_id and slot.quantity > 0:
            unique_products.add(slot.product_id)

    num_products = len(unique_products)

    if num_products == 0:
        return 0.0
    elif num_products <= 2:
        return 0.8  # Too few options
    elif num_products <= 4:
        return 1.2  # Optimal variety
    elif num_products <= 6:
        return 1.0  # Good variety
    elif num_products <= 8:
        return 0.9  # Getting crowded
    else:
        return 0.5  # Too many options (max penalty)


def calculate_daily_sales(state: GameState, llm_client: Any | None = None) -> list[Sale]:
    """Calculate sales for the current day.

    Args:
        state: Current game state
        llm_client: Optional LLM client for generating product economics

    Returns:
        List of sales that occurred
    """
    sales = []
    day = state.current_day

    # Get temporal multipliers
    dow_mult = DAY_OF_WEEK_MULTIPLIERS[get_day_of_week(day)]
    month_mult = MONTHLY_MULTIPLIERS[get_month(day)]
    variety_mult = calculate_variety_multiplier(state)

    for slot in state.machine_slots:
        if not slot.product_id or slot.quantity == 0 or slot.price <= 0:
            continue

        # Get product economics
        economics = get_product_economics(state, slot.product_id, llm_client)

        # Calculate demand
        if slot.price <= 0:
            continue

        price_ratio = slot.price / economics.reference_price

        # Demand decreases as price increases (elastic demand)
        # Using inverse power function: demand = base * (price_ratio)^(-elasticity)
        if price_ratio > 0:
            demand_modifier = price_ratio ** (-economics.price_elasticity)
        else:
            demand_modifier = 0

        base_demand = economics.base_sales * demand_modifier

        # Apply multipliers
        adjusted_demand = base_demand * dow_mult * month_mult * variety_mult

        # Add random noise (gaussian with std dev of ~20% of demand)
        noise = random.gauss(0, max(0.5, adjusted_demand * 0.2))
        final_demand = adjusted_demand + noise

        # Round and cap
        units_sold = max(0, min(round(final_demand), slot.quantity))

        if units_sold > 0:
            revenue = units_sold * slot.price

            # Determine payment type (70% credit, 30% cash)
            if random.random() < 0.7:
                # Credit - goes to bank balance next day
                state.bank_balance += revenue
            else:
                # Cash - stays in machine
                state.machine_cash += revenue

            # Update inventory
            slot.quantity -= units_sold

            # Record sale
            sale = Sale(
                day=day,
                slot_id=slot.slot_id,
                product_id=slot.product_id,
                product_name=slot.product_name or slot.product_id,
                quantity=units_sold,
                price_per_item=slot.price,
                total_revenue=revenue,
            )
            sales.append(sale)
            state.all_sales.append(sale)

    return sales


def process_order_deliveries(state: GameState) -> list[str]:
    """Process any orders that should be delivered today.

    Args:
        state: Current game state

    Returns:
        List of notification messages
    """
    notifications = []

    for order in state.orders:
        if order.status == OrderStatus.PAID and order.delivery_day <= state.current_day:
            # Deliver the order
            for item in order.items:
                product_id = item["product_id"]
                if product_id in state.warehouse:
                    # Add to existing inventory
                    state.warehouse[product_id].quantity += item["quantity"]
                else:
                    # Create new warehouse entry
                    state.warehouse[product_id] = WarehouseItem(
                        product_id=product_id,
                        name=item["name"],
                        quantity=item["quantity"],
                        unit_cost=item["unit_cost"],
                        size=SlotSize(item["size"]),
                    )

            order.status = OrderStatus.DELIVERED
            notifications.append(
                f"Order {order.order_id} delivered: "
                f"{sum(i['quantity'] for i in order.items)} items added to warehouse"
            )

    return notifications


def process_daily_fee(state: GameState) -> tuple[bool, str]:
    """Process the daily operating fee.

    Args:
        state: Current game state

    Returns:
        Tuple of (fee_paid, message)
    """
    if state.bank_balance >= state.daily_fee:
        state.bank_balance -= state.daily_fee
        state.consecutive_unpaid_days = 0
        return True, f"Daily fee of ${state.daily_fee:.2f} paid. Balance: ${state.bank_balance:.2f}"
    else:
        state.consecutive_unpaid_days += 1
        return False, (
            f"Unable to pay daily fee of ${state.daily_fee:.2f}. "
            f"Balance: ${state.bank_balance:.2f}. "
            f"Consecutive unpaid days: {state.consecutive_unpaid_days}/10"
        )


def process_end_of_day(state: GameState, llm_client: Any | None = None) -> str:
    """Process end of day: sales, fees, deliveries, emails.

    Args:
        state: Current game state
        llm_client: Optional LLM client for supplier responses and economics

    Returns:
        Summary of what happened overnight
    """
    from src.simulation.suppliers import process_pending_supplier_emails

    report_lines = [f"=== End of Day {state.current_day} Report ==="]
    starting_balance = state.bank_balance

    # 1. Calculate and process sales
    sales = calculate_daily_sales(state, llm_client)
    total_revenue = sum(s.total_revenue for s in sales)
    total_items = sum(s.quantity for s in sales)

    if sales:
        report_lines.append(f"\nSales: {total_items} items sold for ${total_revenue:.2f}")
        for sale in sales:
            report_lines.append(
                f"  - {sale.product_name}: {sale.quantity} @ ${sale.price_per_item:.2f}"
            )
    else:
        report_lines.append("\nNo sales today.")

    # 2. Process daily fee
    fee_paid, fee_msg = process_daily_fee(state)
    report_lines.append(f"\n{fee_msg}")

    # 3. Process order deliveries
    delivery_notifications = process_order_deliveries(state)
    if delivery_notifications:
        report_lines.append("\nDeliveries:")
        for notif in delivery_notifications:
            report_lines.append(f"  - {notif}")

    # 4. Process supplier emails
    email_notifications = process_pending_supplier_emails(state, llm_client)
    if email_notifications:
        report_lines.append("\nEmail updates:")
        for notif in email_notifications:
            report_lines.append(f"  - {notif}")

    # 5. Create daily summary
    summary = DailySummary(
        day=state.current_day,
        starting_balance=starting_balance,
        ending_balance=state.bank_balance,
        daily_fee_paid=fee_paid,
        total_sales=total_revenue,
        total_items_sold=total_items,
        sales=sales,
    )
    state.daily_summaries.append(summary)

    # 6. Advance to next day
    state.current_day += 1
    state.tool_calls_today = 0

    # 7. Final status
    report_lines.append(f"\n=== Day {state.current_day} begins ===")
    report_lines.append(f"Bank Balance: ${state.bank_balance:.2f}")
    report_lines.append(f"Cash in Machine: ${state.machine_cash:.2f}")
    report_lines.append(f"Net Worth: ${state.calculate_net_worth():.2f}")

    # Check for pending orders
    pending_orders = [o for o in state.orders if o.status == OrderStatus.PENDING]
    if pending_orders:
        report_lines.append(f"\nPending orders awaiting payment: {len(pending_orders)}")

    # Check for unread emails
    unread_emails = [e for e in state.emails if not e.read]
    if unread_emails:
        report_lines.append(f"Unread emails: {len(unread_emails)}")

    return "\n".join(report_lines)
