repos:
  - repo: local
    hooks:
      - id: fix
        name: fix
        entry: uv run poe fix
        language: system
        pass_filenames: false
        always_run: true

      - id: check
        name: check
        entry: uv run poe check
        language: system
        pass_filenames: false
        always_run: true