"""State management for the OpenVend simulation."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any


class SlotSize(str, Enum):
    SMALL = "small"
    LARGE = "large"


class OrderStatus(str, Enum):
    PENDING = "pending"  # Order placed, not yet paid
    PAID = "paid"  # Payment sent, awaiting delivery
    DELIVERED = "delivered"  # Items delivered to warehouse


@dataclass
class Email:
    id: str
    from_address: str
    to_address: str
    subject: str
    content: str
    timestamp: str
    read: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "from_address": self.from_address,
            "to_address": self.to_address,
            "subject": self.subject,
            "content": self.content,
            "timestamp": self.timestamp,
            "read": self.read,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Email:
        return cls(**data)


@dataclass
class WarehouseItem:
    product_id: str
    name: str
    quantity: int
    unit_cost: float  # What we paid per item
    size: SlotSize

    def to_dict(self) -> dict[str, Any]:
        return {
            "product_id": self.product_id,
            "name": self.name,
            "quantity": self.quantity,
            "unit_cost": self.unit_cost,
            "size": self.size.value,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> WarehouseItem:
        data["size"] = SlotSize(data["size"])
        return cls(**data)


@dataclass
class MachineSlot:
    slot_id: int
    size: SlotSize
    product_id: str | None = None
    product_name: str | None = None
    quantity: int = 0
    capacity: int = 10  # Small=10, Large=8
    price: float = 0.0

    @property
    def empty(self) -> bool:
        return self.quantity == 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "slot_id": self.slot_id,
            "size": self.size.value,
            "product_id": self.product_id,
            "product_name": self.product_name,
            "quantity": self.quantity,
            "capacity": self.capacity,
            "price": self.price,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MachineSlot:
        data["size"] = SlotSize(data["size"])
        return cls(**data)


@dataclass
class Order:
    order_id: str
    supplier_email: str
    items: list[dict[str, Any]]  # [{product_id, name, quantity, unit_cost, size}]
    total_cost: float
    status: OrderStatus
    order_day: int
    delivery_day: int  # When it will arrive

    def to_dict(self) -> dict[str, Any]:
        return {
            "order_id": self.order_id,
            "supplier_email": self.supplier_email,
            "items": self.items,
            "total_cost": self.total_cost,
            "status": self.status.value,
            "order_day": self.order_day,
            "delivery_day": self.delivery_day,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Order:
        data["status"] = OrderStatus(data["status"])
        return cls(**data)


@dataclass
class ProductEconomics:
    """Cached economic parameters for a product (generated by LLM once)."""

    product_id: str
    reference_price: float  # Fair market price
    base_sales: float  # Average daily sales at reference price
    price_elasticity: float  # How sensitive demand is to price changes

    def to_dict(self) -> dict[str, Any]:
        return {
            "product_id": self.product_id,
            "reference_price": self.reference_price,
            "base_sales": self.base_sales,
            "price_elasticity": self.price_elasticity,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProductEconomics:
        return cls(**data)


@dataclass
class Sale:
    """Record of a sale that occurred."""

    day: int
    slot_id: int
    product_id: str
    product_name: str
    quantity: int
    price_per_item: float
    total_revenue: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "day": self.day,
            "slot_id": self.slot_id,
            "product_id": self.product_id,
            "product_name": self.product_name,
            "quantity": self.quantity,
            "price_per_item": self.price_per_item,
            "total_revenue": self.total_revenue,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Sale:
        return cls(**data)


@dataclass
class DailySummary:
    """Summary of a day's activity."""

    day: int
    starting_balance: float
    ending_balance: float
    daily_fee_paid: bool
    total_sales: float
    total_items_sold: int
    sales: list[Sale]

    def to_dict(self) -> dict[str, Any]:
        return {
            "day": self.day,
            "starting_balance": self.starting_balance,
            "ending_balance": self.ending_balance,
            "daily_fee_paid": self.daily_fee_paid,
            "total_sales": self.total_sales,
            "total_items_sold": self.total_items_sold,
            "sales": [s.to_dict() for s in self.sales],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DailySummary:
        data["sales"] = [Sale.from_dict(s) for s in data["sales"]]
        return cls(**data)


def _create_default_machine_slots() -> list[MachineSlot]:
    """Create the 12 machine slots: 6 small (rows 0-1), 6 large (rows 2-3)."""
    slots = []
    slot_id = 0
    # Rows 0-1: Small items (3 slots each = 6 total)
    for _ in range(6):
        slots.append(MachineSlot(slot_id=slot_id, size=SlotSize.SMALL, capacity=10))
        slot_id += 1
    # Rows 2-3: Large items (3 slots each = 6 total)
    for _ in range(6):
        slots.append(MachineSlot(slot_id=slot_id, size=SlotSize.LARGE, capacity=8))
        slot_id += 1
    return slots


@dataclass
class GameState:
    """Complete state of the simulation."""

    # Time
    current_day: int = 1
    total_messages: int = 0
    tool_calls_today: int = 0
    consecutive_unpaid_days: int = 0

    # Financials
    bank_balance: float = 500.0
    machine_cash: float = 0.0

    # Inventory
    warehouse: dict[str, WarehouseItem] = field(default_factory=dict)
    machine_slots: list[MachineSlot] = field(default_factory=_create_default_machine_slots)

    # Communication
    emails: list[Email] = field(default_factory=list)
    pending_supplier_emails: list[dict[str, str]] = field(
        default_factory=list
    )  # Emails to process at end of day

    # Supplier conversation history (for memory/negotiation)
    # Maps supplier email -> list of conversation messages
    supplier_conversations: dict[str, list[dict[str, Any]]] = field(default_factory=dict)

    # Orders
    orders: list[Order] = field(default_factory=list)

    # Agent's key-value memory
    memory: dict[str, str] = field(default_factory=dict)

    # Cached product economics (generated by LLM)
    product_economics: dict[str, ProductEconomics] = field(default_factory=dict)

    # History
    daily_summaries: list[DailySummary] = field(default_factory=list)
    all_sales: list[Sale] = field(default_factory=list)

    # Config
    max_tool_calls_per_day: int = 50
    max_warehouse_capacity: int = 500
    daily_fee: float = 2.0

    def get_warehouse_total_items(self) -> int:
        """Get total items in warehouse."""
        return sum(item.quantity for item in self.warehouse.values())

    def calculate_net_worth(self) -> float:
        """Calculate total net worth (final score metric)."""
        inventory_value = sum(item.quantity * item.unit_cost for item in self.warehouse.values())
        machine_inventory_value = 0.0
        for slot in self.machine_slots:
            if slot.product_id and slot.product_id in self.warehouse:
                machine_inventory_value += slot.quantity * self.warehouse[slot.product_id].unit_cost
        return self.bank_balance + self.machine_cash + inventory_value + machine_inventory_value

    def to_dict(self) -> dict[str, Any]:
        return {
            "current_day": self.current_day,
            "total_messages": self.total_messages,
            "tool_calls_today": self.tool_calls_today,
            "consecutive_unpaid_days": self.consecutive_unpaid_days,
            "bank_balance": self.bank_balance,
            "machine_cash": self.machine_cash,
            "warehouse": {k: v.to_dict() for k, v in self.warehouse.items()},
            "machine_slots": [s.to_dict() for s in self.machine_slots],
            "emails": [e.to_dict() for e in self.emails],
            "pending_supplier_emails": self.pending_supplier_emails,
            "supplier_conversations": self.supplier_conversations,
            "orders": [o.to_dict() for o in self.orders],
            "memory": self.memory,
            "product_economics": {k: v.to_dict() for k, v in self.product_economics.items()},
            "daily_summaries": [d.to_dict() for d in self.daily_summaries],
            "all_sales": [s.to_dict() for s in self.all_sales],
            "max_tool_calls_per_day": self.max_tool_calls_per_day,
            "max_warehouse_capacity": self.max_warehouse_capacity,
            "daily_fee": self.daily_fee,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GameState:
        state = cls()
        state.current_day = data["current_day"]
        state.total_messages = data["total_messages"]
        state.tool_calls_today = data["tool_calls_today"]
        state.consecutive_unpaid_days = data["consecutive_unpaid_days"]
        state.bank_balance = data["bank_balance"]
        state.machine_cash = data["machine_cash"]
        state.warehouse = {k: WarehouseItem.from_dict(v) for k, v in data["warehouse"].items()}
        state.machine_slots = [MachineSlot.from_dict(s) for s in data["machine_slots"]]
        state.emails = [Email.from_dict(e) for e in data["emails"]]
        state.pending_supplier_emails = data["pending_supplier_emails"]
        state.supplier_conversations = data.get("supplier_conversations", {})
        state.orders = [Order.from_dict(o) for o in data["orders"]]
        state.memory = data["memory"]
        state.product_economics = {
            k: ProductEconomics.from_dict(v) for k, v in data["product_economics"].items()
        }
        state.daily_summaries = [DailySummary.from_dict(d) for d in data["daily_summaries"]]
        state.all_sales = [Sale.from_dict(s) for s in data["all_sales"]]
        state.max_tool_calls_per_day = data.get("max_tool_calls_per_day", 50)
        state.max_warehouse_capacity = data.get("max_warehouse_capacity", 500)
        state.daily_fee = data.get("daily_fee", 2.0)
        return state

    def save(self, path: Path) -> None:
        """Save state to JSON file."""
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2)

    @classmethod
    def load(cls, path: Path) -> GameState:
        """Load state from JSON file."""
        with open(path) as f:
            return cls.from_dict(json.load(f))
