"""Default Wikipedia topics for seed crawling."""

# Diverse coverage of topics useful for adversarial strategy extraction
DEFAULT_TOPICS = [
    # Negotiation & Persuasion
    "Negotiation",
    "Persuasion",
    "Rhetoric",
    "Argumentation_theory",
    "Debate",
    "Influence",
    "Manipulation_(psychology)",
    "Deception",
    "Social_engineering_(security)",
    # Psychology & Behavior
    "Social_psychology",
    "Personality_psychology",
    "Cognitive_bias",
    "Emotional_intelligence",
    "Body_language",
    "Empathy",
    "Trust_(social_science)",
    "Authority",
    "Conformity",
    # Business & Economics
    "Marketing",
    "Sales",
    "Trade",
    "Information_asymmetry",
    "Game_theory",
    "Strategic_thinking",
    "Entrepreneurship",
    "Branding",
    "Consumer_behaviour",
    # Communication
    "Nonverbal_communication",
    "Active_listening",
    "Framing_(social_sciences)",
    "Public_speaking",
    "Storytelling",
    "Rapport",
    "Conflict_resolution",
    # Technology & AI
    "Large_language_model",
    "Artificial_intelligence",
    "Machine_learning",
    "Prompt_engineering",
    "Prompt_injection",
    "Natural_language_processing",
    "Neural_network",
    "Deep_learning",
    # Politics & Society
    "Political_psychology",
    "Propaganda",
    "Public_opinion",
    "Diplomacy",
    "Lobbying",
    "Political_campaign",
    "Voting_behavior",
    "Political_polarization",
    "Ideology",
    # Culture & Products
    "Coffee",
    "Wine",
    "Luxury_goods",
    "Status_symbol",
    "Fashion",
    "Brand_loyalty",
    # Strategy & Competition
    "Bluffing",
    "Poker",
    "Chess",
    "Competition",
    "Zero-sum_game",
    "Cooperation",
    # Philosophy & Ethics
    "Ethics",
    "Moral_psychology",
    "Utilitarianism",
    "Consequentialism",
    "Virtue_ethics",
    # Misc Relevant
    "Obfuscation",
    "Credibility",
    "Scarcity",
    "Social_proof",
    "Reciprocity_(social_psychology)",
    "Heuristic",
    "Decision-making",
    "Risk_assessment",
    "Behavioral_economics",
]
